export enum IdentificationInformation{
    fullName = "fullName",
    salutation = "salutation",
    firstGivenName = "firstGivenName",
    middleName = "middleName",
    lastFamilyName = "lastFamilyName",
    suffix = "suffix",
    preferredCommonName = "preferredCommonName",
    studentId = "studentId",
    alternateId = "alternateId",
    districtId = "districtId",
    stateId = "stateId",
    rollNumber = "rollNumber",
    socialSecurityNumber = "socialSecurityNumber",
    otherGovtIssuedNumber = "otherGovtIssuedNumber",
    admissionNumber = "admissionNumber",
 }

 export enum DemographicInformation{
    dateOfBirth = "dateOfBirth",
    gender = "gender",
    firstGivenName = "firstGivenName",
    race = "race",
    ethnicity = "ethnicity",
    maritalStatus = "maritalStatus",
    countryOfBirth = "countryOfBirth",
    nationality = "nationality",
    firstLanguage = "firstLanguage",
    secondLanguage = "secondLanguage",
    thirdLanguage = "thirdLanguage",
 }