//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace opensis.data.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CityData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CityData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("opensis.data.Data.CityData", typeof(CityData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{&quot;id&quot;:1,&quot;name&quot;:&quot;Eshkashem&quot;,&quot;stateid&quot;:1},{&quot;id&quot;:2,&quot;name&quot;:&quot;Fayzabad&quot;,&quot;stateid&quot;:1},{&quot;id&quot;:3,&quot;name&quot;:&quot;Jurm&quot;,&quot;stateid&quot;:1},{&quot;id&quot;:4,&quot;name&quot;:&quot;Khandud&quot;,&quot;stateid&quot;:1},{&quot;id&quot;:5,&quot;name&quot;:&quot;Qal&apos;eh-ye Panjeh&quot;,&quot;stateid&quot;:1},{&quot;id&quot;:6,&quot;name&quot;:&quot;Bala Morghab&quot;,&quot;stateid&quot;:2},{&quot;id&quot;:7,&quot;name&quot;:&quot;Qal&apos;eh-ye Naw&quot;,&quot;stateid&quot;:2},{&quot;id&quot;:8,&quot;name&quot;:&quot;Andarab&quot;,&quot;stateid&quot;:3},{&quot;id&quot;:9,&quot;name&quot;:&quot;Baghlan&quot;,&quot;stateid&quot;:3},{&quot;id&quot;:10,&quot;name&quot;:&quot;Dahaneh-ye Ghawri&quot;,&quot;stateid&quot;:3},{&quot;id&quot;:11,&quot;name&quot;:&quot;Nahrin&quot;,&quot;stateid&quot;:3},{&quot;id&quot;:12,&quot;name&quot;:&quot;Pol-e Khumri&quot;,&quot;stateid&quot;:3},{&quot;id&quot;:13,&quot;name&quot;:&....
        /// </summary>
        public static string CityJSON {
            get {
                return ResourceManager.GetString("CityJSON", resourceCulture);
            }
        }
    }
}
